name: Android CI

on:
  push:
    branches:
      - Rxjava1.x
      - RxJava2.x
      - RxJava3.x
  pull_request:
    branches:
      - RxJava1.x
      - RxJava2.x
      - RxJava3.x

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Gradle Build
      run: ./gradlew clean build
    - name: Gradle Check
      run: ./gradlew check -x test
